name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master  # Change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your GCP project ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Your service account key stored in GitHub Secrets

      - name: Authenticate Docker to GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:$GITHUB_SHA .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \  # Adjust the region as needed
            --allow-unauthenticated \  # Allow unauthenticated access (public)
            --port 8080  # Specify the port your Flask app is running on
